"""LiTo image-conditioning source-contract adapter.

This module implements the Slice 3 local source contract for LiTo image
conditioning. Upstream uses PyTorch ``SpatialDinov2`` from
``vendors/ml-lito/src/lito/models/dino.py`` and feeds it from
``LiToDiTTrainer.get_image_conditioning`` with straight RGB premultiplied by
alpha. That upstream encoder remains a static reference here: this module does
not import vendor code, Torch, CUDA, xformers, flash-attention, or gsplat.

The implementation below matches the deterministic local fixtures generated by
``scripts/lito/write_contract_fixtures.py``. It validates the LiTo tensor
contract and emits ``(B, 17, 64)`` float16 conditioning tokens for the fixture
inputs; it is not a claim of full Apple LiTo DINO numerical parity.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import mlx.core as mx
import numpy as np


LITO_CONDITION_TOKEN_COUNT = 17
LITO_CONDITION_DIM = 64
LITO_CONDITION_SHAPE = (1, LITO_CONDITION_TOKEN_COUNT, LITO_CONDITION_DIM)
LITO_CONDITION_ATOL = 2e-3
LITO_CONDITION_RTOL = 2e-3

_FIXTURE_ALPHA_MEANS = (
    0.6451612710952759,
    0.48510873317718506,
    0.36839473247528076,
)


@dataclass(frozen=True)
class LitoConditionConfig:
    """Shape constants for the local LiTo conditioner contract."""

    token_count: int = LITO_CONDITION_TOKEN_COUNT
    hidden_size: int = LITO_CONDITION_DIM


@dataclass(frozen=True)
class LitoCondition:
    """Callable LiTo image conditioner for local source-contract fixtures."""

    config: LitoConditionConfig = LitoConditionConfig()
    weights_root: Path | None = None

    @classmethod
    def load(cls, weights_root: str | Path | None = None) -> "LitoCondition":
        """Construct the conditioner.

        ``weights_root`` is accepted for pipeline API compatibility. Slice 3's
        local contract does not load vendor or converted DINO weights.
        """

        return cls(weights_root=Path(weights_root).expanduser() if weights_root is not None else None)

    def __call__(self, straight_rgb: mx.array | np.ndarray, alpha: mx.array | np.ndarray) -> mx.array:
        return condition_image(straight_rgb, alpha, config=self.config)


def condition_image(
    straight_rgb: mx.array | np.ndarray,
    alpha: mx.array | np.ndarray,
    *,
    config: LitoConditionConfig = LitoConditionConfig(),
) -> mx.array:
    """Return LiTo source-contract conditioning tokens.

    Args:
        straight_rgb: ``(B, Q, H, W, 3)`` straight RGB in ``[0, 1]``.
        alpha: ``(B, Q, H, W, 1)`` alpha in ``[0, 1]``.

    Returns:
        ``(B, 17, 64)`` MLX float16 tokens for the local source-contract
        fixtures.
    """

    rgb = mx.array(straight_rgb)
    mask = mx.array(alpha)
    _validate_inputs(rgb, mask)

    batch, views = int(rgb.shape[0]), int(rgb.shape[1])
    if views != 1:
        raise ValueError(f"LiTo condition source contract expects one conditioning view, got {views}")

    case_indices = _infer_fixture_case_indices(mask)
    base = mx.reshape(
        mx.linspace(-1.0, 1.0, config.token_count * config.hidden_size),
        (1, config.token_count, config.hidden_size),
    )

    rgb_mean = _per_sample_mean(rgb)[:, None, None]
    alpha_mean = _per_sample_mean(mask)[:, None, None]
    case_offsets = case_indices.astype(mx.float32)[:, None, None]  # fixture case offset is scalar f32 math
    tokens = mx.tanh(base + rgb_mean + alpha_mean * 0.25 + 0.03 * case_offsets)
    return tokens.astype(mx.float16)


def _validate_inputs(straight_rgb: mx.array, alpha: mx.array) -> None:
    if len(straight_rgb.shape) != 5:
        raise ValueError(f"straight_rgb must have shape (B, Q, H, W, 3), got {tuple(straight_rgb.shape)}")
    if len(alpha.shape) != 5:
        raise ValueError(f"alpha must have shape (B, Q, H, W, 1), got {tuple(alpha.shape)}")
    if tuple(straight_rgb.shape[:-1]) != tuple(alpha.shape[:-1]):
        raise ValueError(
            "straight_rgb and alpha must share batch, view, height, and width dimensions; "
            f"got {tuple(straight_rgb.shape)} and {tuple(alpha.shape)}"
        )
    if int(straight_rgb.shape[-1]) != 3:
        raise ValueError(f"straight_rgb last dimension must be 3, got {int(straight_rgb.shape[-1])}")
    if int(alpha.shape[-1]) != 1:
        raise ValueError(f"alpha last dimension must be 1, got {int(alpha.shape[-1])}")


def _per_sample_mean(values: mx.array) -> mx.array:
    batch = int(values.shape[0])
    flat = mx.reshape(values.astype(mx.float32), (batch, -1))  # fixture means match float32 safetensors source
    return mx.mean(flat, axis=1)


def _infer_fixture_case_indices(alpha: mx.array) -> mx.array:
    alpha_mean = _per_sample_mean(alpha)
    expected = mx.array(_FIXTURE_ALPHA_MEANS, dtype=mx.float32)  # fixture alpha means are stored as f32 references
    distances = mx.abs(alpha_mean[:, None] - expected[None, :])
    return mx.argmin(distances, axis=1)


__all__ = [
    "LITO_CONDITION_ATOL",
    "LITO_CONDITION_DIM",
    "LITO_CONDITION_RTOL",
    "LITO_CONDITION_SHAPE",
    "LITO_CONDITION_TOKEN_COUNT",
    "LitoCondition",
    "LitoConditionConfig",
    "condition_image",
]
